version: "3.8"

services:
  app:
    ## O "." indica a imagem do Docker seá construida no diretório atual
    build: .
    command: /bin/sh -c "npm install && npm start"
    ## Mapeia a porta 5000 do container para a porta 5000 da máquina
    ports: 
      - "5000:5000"
    ## Monta o diretório atual da máquina host no diretorio /usr/app do container
    volumes:
      - .:/usr/app
    ## Indica que o serviço app depende so serviço db
    depends_on:
     - db

  db:
    image: mysql:8.0
    ## Configura o container para reiniciar automaticamente caso ele pare.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senai@604
      MYSQL_DATABASE: vio_maria
      ## Mapeia a porta 3306 do container para a porta 3306 da máquina
    ports:
      - "3307:3306"
    volumes: 
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: